# Generated by Django 3.2.8 on 2021-10-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20211027_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bot',
            new_name='bots',
        ),
    ]
